version: '3.8'
services:
  app:
    build:
      context: ./jitr-platform
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypass
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    depends_on:
      - db
    volumes:
      - ./jitr-platform:/home/app

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    volumes:
      - ./jitr-db/init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres_data:
